### ISSUE TITLE
screen 0.0.3 requires Dart SDK version <2.0.0

### ISSUE THREAD

**Issue by jobel-code** [clovisnicolas/flutter_screen#4]
Hej can you remove the SDK restriction version?
I received The current Dart SDK version is 2.1.0-dev.0.0.flutter-be6309690f.

Because screen 0.0.3 requires SDK version <2.0.0 and no versions of screen match >0.0.3 <0.1.0, screen ^0.0.3 is forbidden.
So, because depends on screen ^0.0.3, version solving failed.
pub get failed (1)

Thanks in advance!

**Comment by ened** [comment]
Trying using the branch at #5 - and let us know how it works for you.

**Comment by jobel-code** [comment]
Thanks! problem solved as you suggested by using in pubspec.yaml:

```
screen:
    git:
      url: https://github.com/ened/flutter_screen.git
      ref: sdk-2

```
